version: '3'
services:
    db:
        image: postgres:13.4-alpine
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: adminpw
        ports:
        - 5432:5432
    web:
        build: .
        image: cjpalmer/gallery:0.1.0
        volumes:
        - ./app:/app
        environment:
            FLASK_DEBUG: 1
        ports:
        - 80:5000
