version: '3'
services:
    db:
        image: postgres:13.4-alpine
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: adminpw
        ports:
        - 5432:5432
    web:
        image: nginx:1.17
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - gallery_data:/data/images
        ports:
        - 80:80
        depends_on:
        - gallery
    gallery:
        build: .
        image: cjpalmer/gallery:1.0.0
        volumes:
        - gallery_data:/app/gallery
        - ./app:/app
        environment:
            FLASK_DEBUG: 1
        depends_on:
        - db
volumes:
    gallery_data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /mnt/gallery_data
