version: '3'
services:
    navigator:
        build: ./navigator
        image: cjpalmer/gallery-navigator:1.2.0
        volumes:
        - gallery_data:/app/gallery
        environment:
            FLASK_DEBUG: 1
    server:
        build: ./server
        image: cjpalmer/gallery-server:1.1.0
        volumes:
        - gallery_data:/data/images
        ports:
        - 80:80
        depends_on:
        - navigator
volumes:
    gallery_data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /mnt/gallery_data
