version: '3'
networks:
    proxy:
        external: true
    backend:
        driver: overlay
services:
    navigator:
        image: cjpalmer/gallery-navigator:1.6.0
        volumes:
        - gallery_data:/app/gallery
        networks:
        - backend
    server:
        image: cjpalmer/gallery-server:1.6.0
        volumes:
        - gallery_data:/data/images
        depends_on:
        - navigator
        networks:
        - backend
        - proxy
volumes:
    gallery_data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /mnt/gallery_data
