version: '3'
services:
    navigator:
        build: ./navigator
        image: cjpalmer/gallery-navigator:1.4.0
        volumes:
#       - ./navigator/app:/app # dev testing
        - gallery_data_dev:/app/gallery
        environment:
            FLASK_DEBUG: 1
    server:
        build: ./server
        image: cjpalmer/gallery-server:1.4.0
        volumes:
        - gallery_data_dev:/data/images
        ports:
        - 80:80
        depends_on:
        - navigator
volumes:
    gallery_data_dev:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /mnt/gallery_data_dev
